# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: self
      type: git
      ref: fe-develop

trigger:
  - fe-develop

pool:
  vmImage: ubuntu-latest

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
  - checkout: self
    submodules: false

  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: '16.x'

  - script: |
      npm install
    displayName: Install node modules
    workingDirectory: ./PreciseAlloy.Frontend

  - script: |
      npm run eshn
    displayName: Generate statis site
    workingDirectory: ./PreciseAlloy.Frontend

  - task: AzureStaticWebApp@0
    displayName: Deploy to Azure Static Web App
    inputs:
      app_location: './PreciseAlloy.Frontend/dist/static'
      api_location: ''
      output_location: ''
      skip_app_build: true
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
