# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: self
      type: git
      ref: fe-develop

trigger:
  - fe-develop

pool:
  vmImage: ubuntu-latest

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
  - checkout: self
    submodules: false

  - script: |
      curl -fsSL https://bun.sh/install | bash
      echo '##vso[task.prependpath]~/.bun/bin'
    displayName: Install bun
    workingDirectory: PreciseAlloy.Frontend

  - script: |
      bun install
    displayName: Install node modules
    workingDirectory: ./PreciseAlloy.Frontend

  - script: |
      bun run eshn
    displayName: Generate static site
    workingDirectory: PreciseAlloy.Frontend

  - task: AzureStaticWebApp@0
    displayName: Deploy to Azure Static Web App
    inputs:
      app_location: PreciseAlloy.Frontend/dist/static
      api_location: ''
      output_location: ''
      skip_app_build: true
      skip_api_build: true
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
