# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: self
      type: git
      ref: fe-release

trigger:
  - fe-release

pool:
  vmImage: ubuntu-latest

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  CustomReviewId: 'ae28c67f-731c-48ab-a8b1-6e3bd2ea71a2' # Check https://www.tuyen.xyz/optimizely-cms/frontend/integration/ for how to get this ID

steps:
  - checkout: self
    clean: true
    persistCredentials: true
    fetchDepth: 0

  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '16.x'

  - script: |
      git config --global user.email "VanTuyen.Pham@episerver.com"
      git config --global user.name "Tuyen Pham"
      git fetch origin develop:develop
      git merge develop
    displayName: 'Create git branch'

  - script: |
      npm install
      npm run inte
      git checkout -- .
    displayName: 'Run npm install and inte'
    workingDirectory: ./PreciseAlloy.Frontend

  - script: |
      git add .
      git commit -m "Create release package"
      git push origin HEAD:fe-release-inte-package -f
    displayName: 'Create release package'

  - task: PowerShell@2
    displayName: 'PR to develop'
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)/PreciseAlloy.Frontend/.build/integration.ps1
      pwsh: true
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      CUSTOM_REPOSITORY_NAME: $(Build.Repository.Name)
      CUSTOM_SOURCE_BRANCH: 'fe-release-inte-package'
      CUSTOM_TARGET_BRANCH: 'develop'
      CUSTOM_REVIEWER_ID: $(CustomReviewId)

  - task: PowerShell@2
    displayName: 'PR to fe-develop'
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)/PreciseAlloy.Frontend/.build/integration.ps1
      pwsh: true
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      CUSTOM_REPOSITORY_NAME: $(Build.Repository.Name)
      CUSTOM_SOURCE_BRANCH: 'fe-release-inte-package'
      CUSTOM_TARGET_BRANCH: 'fe-develop'
      CUSTOM_REVIEWER_ID: $(CustomReviewId)
